church_django/church_mgs/church_mgs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

church_django/church_mgs/members/urls.py
from django.urls import path
#from .views import HomeView
from . import views
from .views import  *
from django.urls import include
from django.contrib.auth import views as auth_views



#app_name = 'members'



#urlpatterns = [
#    path('attendance/add/', views.add_attendance, name='add_attendance'),
#   path('attendance/', views.attendance_list, name='attendance_list'),
#    path('attendance/ajax_mark/', views.ajax_mark_attendance, name='ajax_mark_attendance'),
#    path('dashboard/', views.post_login_redirect, name='dashboard'),
#    path('export/attendance/excel/', views.export_attendance_excel, name='export_attendance_excel'),
#    path('export/attendance/pdf/', views.export_attendance_pdf, name='export_attendance_pdf'),
#    path('attendance/toggle/',views.ajax_toggle_attendance, name='ajax_toggle_attendance'),
#    path('attendance/chart-data/', views.attendance_chart_data, name='attendance_chart_data'),
#    path('attendance/export/excel/',views.export_attendance_excel, name='export_attendance_excel'),
#    path("", views.home, name = "home"),
#    path("redirect/", views.post_login_redirect, name = "post_login_redirect"),
#    path('dashboard/', views.dashboard, name='dashboard'),
#    path("secretary/dashboard", SecretaryDashboardView.as_view(), name='secretary_dashboard'),
#    path("secretary/announcements/", views.announcement_list, name="announcement_list"),
#    path("secretary/finance/", views.finance_dashboard, name="finance_dashboard"),
#    path("secretary/reports/", views.reports, name="reports"),
#    path("login/", auth_views.LoginView.as_view(
#        template_name="registration/login.html"
#    ), name="login"),
#
#    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
#    #path("admin/dashboard/", views.AdminDashboardView.as_view(), name="admin_dashboard"),
#    path("secretary/dashboard/", views.SecretaryDashboardView.as_view(), name="secretary_dashboard"),
#    path("pastor/dashboard/", views.PastorDashboardView.as_view(), name="pastor_dashboard"),
#    path("members/", views.member_list, name="member_list"),
#    path("<int:pk>/", views.member_detail, name="member_detail"),
#    path("<int:pk>/edit/", views.member_edit, name="member_edit"),
#    path("<int:pk>/delete/", views.member_delete, name="member_delete"),
#    path("add/", views.member_create, name="member_create"),
#    path("secretary/secretary_settings/", views.secretary_settings, name="secretary_settings"),
#    path("members/", member_list, name="member_list"),
#    path("members/<int:pk>/", member_detail, name="member_detail"),
#    path("members/export/excel/", export_members_excel, name="export_members_excel"),
#    path("members/export/pdf/", export_members_pdf, name="export_members_pdf"),
#]



app_name = 'members'  # ← important for namespaces

urlpatterns = [
        path('promise/<int:promise_id>/edit/', views.edit_promise, name='edit_promise'),
        path('promise/<int:promise_id>/delete/', views.delete_promise, name='delete_promise'),
    # Authentication
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    # Home & dashboard
    path("", views.home, name="home"),
    path("redirect/", views.post_login_redirect, name="post_login_redirect"),
    path("dashboard/", views.post_login_redirect, name='dashboard'),
    #path("secretary/dashboard/", views.SecretaryDashboardView.as_view(), name="secretary_dashboard"),
    path("pastor/dashboard/", views.PastorDashboardView.as_view(), name="pastor_dashboard"),

    # Members
    path("members/", views.member_list, name="member_list"),
    path("members/add/", views.member_create, name="member_create"),
    path("members/<int:pk>/", views.member_detail, name="member_detail"),
    path("members/<int:pk>/edit/", views.member_edit, name="member_edit"),
    path("members/<int:pk>/delete/", views.member_delete, name="member_delete"),
    path("members/export/excel/", views.export_members_excel, name="export_members_excel"),
    path("members/export/pdf/", views.export_members_pdf, name="export_members_pdf"),

    # Attendance
   # path("announcements/add_attendance/", views.add_attendance, name="add_attendance"),
    path("add_attendance/", views.attendance_list, name="attendance_list"),
    path("attendance/ajax_mark/", views.ajax_mark_attendance, name="ajax_mark_attendance"),
    path("attendance/toggle/", views.ajax_toggle_attendance, name="ajax_toggle_attendance"),
    path("attendance/chart-data/", views.attendance_chart_data, name="attendance_chart_data"),
    path("export/attendance/excel/", views.export_attendance_excel, name="export_attendance_excel"),
    path("export/attendance/pdf/", views.export_attendance_pdf, name="export_attendance_pdf"),

    # Secretary
    path("secretary/finance/", views.finance_dashboard, name="finance_dashboard"),
    path("secretary/reports/", views.reports, name="reports"),
    path("secretary/secretary_settings/", views.secretary_settings, name="secretary_settings"),
    #path("secretary/dashboard/",views.SecretaryDashboardView.as_view(),name="secretary_dashboard"),
    path("secretary/secretary_dashboard/", views.secretary_dashboard, name="secretary_dashboard"),
    path("ajax/mark-attendance/", views.ajax_mark_attendance, name="ajax_mark_attendance"),
    path("announcements/promises_dashboard/",views.promises_dashboard,name="promises_dashboard"),
    path('announcements/add/', views.add_announcement, name='add_announcement'),
    path('attendance/add_attendance/', views.add_attendance, name='add_attendance'),
    path('promise/add/', views.add_promise, name='add_promise'),
    path("announcements/", views.announcement_dashboard, name="announcement_dashboard"),
    path("announcements/display/", views.announcement_display, name="announcement_display"),
    path("announcements/edit/<int:pk>/", views.announcement_edit, name="announcement_edit"),
    path("announcements/delete/<int:pk>/", views.announcement_delete, name="announcement_delete"),
    path("announcements/export/pdf/", views.export_announcements_pdf, name="export_announcements_pdf"),
    path("announcements/add_announcement/", views.add_announcement, name="add_announcement"),
    path("announcements/slide_show/", views.announcement_slide_show, name="announcement_slide_show"),
    path("announcements/add_promise/", views.add_promise, name="add_promise"),
    path("announcements/export/pdf/", views.export_promises_pdf, name="export_promises_pdf"),
    path("announcements/export/excel/", views.export_promises_excel, name="export_promises_excel"),
    path("finance/tithes_dashboard/", views.tithes_dashboard, name="tithes_dashboard"),
    path("finance/finance_home/", views.finance_home, name="finance_home"),

    #path('tithes/', views.tithes_records, name='tithes_records'),
    path('tithes/add/', views.add_tithe, name='add_tithe'),
    path('tithes/edit/<int:pk>/', views.edit_tithe, name='edit_tithe'),
    path('tithes/delete/<int:pk>/', views.delete_tithe, name='delete_tithe'),
    path('tithes/pdf/', views.tithes_pdf, name='tithes_pdf'),
    
]   

church_django/church_mgs/members/views.py
from django.contrib import messages
from django.utils import timezone
from datetime import date, timedelta
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.db.models import Count,  Q, Sum
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from lxml.objectify import annotate
from xhtml2pdf import pisa
import openpyxl
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from .models  import Attendance, Member, DailyChurchReport, Promise, Income, Expense, Announcement
from django.views.generic import TemplateView
from django.contrib.auth.mixins import UserPassesTestMixin
from .utils import is_admin, is_secretary
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from reportlab.pdfgen import canvas
from django import forms

from django.contrib.auth.decorators import login_required, user_passes_test





@login_required
def post_login_redirect(request):
    user = request.user

    # Django Admin users
    if user.is_superuser or user.is_staff:
        return redirect("/admin/")

    if user.groups.filter(name="Secretary").exists():
        return redirect("members:secretary_dashboard")

    if user.groups.filter(name="Pastor").exists():
        return redirect("members:pastor_dashboard")

    # fallback
    return redirect("members:home")


class AttendanceDashboardView(TemplateView):
    template_name = 'attendance/secretary_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        qs = Attendance.objects.all()

        # Filters
        start = self.request.GET.get('start')
        end = self.request.GET.get('end')
        service = self.request.GET.get('service')

        if start:
            qs = qs.filter(date__gte=start)
        if end:
            qs = qs.filter(date__lte=end)
        if service:
            qs = qs.filter(service=service)

        context['total'] = qs.count()
        context['present'] = qs.filter(present=True).count()
        context['absent'] = qs.filter(present=False).count()
        context['services'] = Attendance.objects.values_list('service', flat=True).distinct()

        return context


class PastorDashboardView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = "pastor/secretary_dashboard.html"

    def test_func(self):
        return self.request.user.groups.filter(name="Pastor").exists()


from django.db.models.functions import TruncWeek, TruncMonth

weekly = (
    Attendance.objects
    .annotate(week=TruncWeek('date'))
    .values('week')
    .annotate(total=Count('id'))
)

monthly = (
    Attendance.objects
    .annotate(month=TruncMonth('date'))
    .values('month')
    .annotate(total=Count('id'))
)


@login_required
def announcements_dashboard(request):
    today = now().date()

    report, created = DailyChurchReport.objects.get_or_create(
        date=today,
        defaults={
            'service_type': 'Sunday',
            'announcements': '',
            'total_attendance': 0,
            'offering_amount': 0,
            'created_by': request.user
        }
    )

    # 🔹 AUTO-PULL attendance summary
    attendance_summary = Attendance.objects.filter(
        date=today,
        service_type=report.service_type
    ).aggregate(
        total_present=Count('id', filter=Q(present=True)),
        total_absent=Count('id', filter=Q(present=False)),
        total_members=Count('id')
    )

    # 🔹 Auto-fill attendance
    report.total_attendance = attendance_summary['total_present'] or 0
    report.save(update_fields=['total_attendance'])

    if request.method == "POST":
        # 🔹 Update report fields
        report.service_type = request.POST.get("service_type")
        report.announcements = request.POST.get("announcements")
        report.offering_amount = request.POST.get("offering_amount") or 0
        report.promises_amount = request.POST.get("promises_amount") or 0
        report.special_notes = request.POST.get("special_notes")
        report.created_by = request.user
        report.save()

        # 🔹 Get promise fields safely
        member_name = request.POST.get("promise_member")
        promise_type = request.POST.get("promise_type")
        amount = request.POST.get("promise_amount")
        item = request.POST.get("promise_item")
        due_date = request.POST.get("promise_due_date")

        # 🔹 Save promise only if filled
        if member_name and promise_type:
            Promise.objects.create(
                report=report,
                member_name=member_name,
                promise_type=promise_type,
                amount=amount if promise_type == "money" else None,
                item_description=item if promise_type == "item" else "",
                due_date=due_date or None
            )

        return redirect("members:announcements_dashboard")
    promises = Promise.objects.filter(report=report)
    promise_filter = request.GET.get('promise_filter', 'all')
    if promise_filter == 'overdue':
        promises = promises.filter(due_date__lt=today, fulfilled=False)
    elif promise_filter == 'fulfilled':
        promises = promises.filter(fulfilled=True)
    elif promise_filter == 'unfulfilled':
        promises = promises.filter(fulfilled=False)

    return render(request, "announcements/announcements_dashboard.html", {
        "report": report,
        "today": today,
        "attendance_summary": attendance_summary,
        "promises": promises,
        "request": request,
    })

@login_required
def add_announcement(request): 
    if request.method == "POST":
        title = request.POST.get("title")
        message = request.POST.get("message")

        if title and message:
            Announcement.objects.create(
                title=title,
                message=message,
                created_by=request.user
            )
            return redirect("members:announcement_dashboard")

    return render(request, "announcements/add_announcement.html")

@login_required
@user_passes_test(is_secretary)
def announcement_edit(request, pk):
    announcement = get_object_or_404(Announcement, pk=pk)

    if request.method == "POST":
        announcement.title = request.POST.get("title")
        announcement.message = request.POST.get("message")
        announcement.save()
        return redirect("members:announcement_dashboard")

    return render(request, "announcements/announcement_edit.html", {
        "announcement": announcement
    })


@login_required
@user_passes_test(is_secretary)
def announcement_delete(request, pk):
    announcement = get_object_or_404(Announcement, pk=pk)

    if request.method == "POST":
        announcement.delete()
        return redirect("members:announcement_dashboard")

    return redirect("members:announcement_dashboard")
@login_required
@user_passes_test(is_secretary)
def announcement_slide_show(request):
    today = date.today()

    announcements = Announcement.objects.filter(
        date=today,
        is_active=True
    ).order_by("created_at")

    return render(request, "announcements/display.html", {
        "announcements": announcements,
        "today": today,
    })



def announcement_display(request):
    today = date.today()

    announcements = Announcement.objects.filter(
        date=today,
        is_active=True
    ).order_by("created_at")

    return render(request, "announcements/display.html", {
        "announcements": announcements,
        "today": today,
    })





@login_required
def export_announcements_pdf(request):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="announcements.pdf"'

    p = canvas.Canvas(response)
    y = 800

    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, y, "Church Announcements")
    y -= 30

    p.setFont("Helvetica", 10)
    for ann in Announcement.objects.all().order_by("-created_at"):
        if y < 50:
            p.showPage()
            y = 800

        p.drawString(50, y, f"{ann.title} ({ann.created_at.strftime('%d %b %Y')})")
        y -= 15
        p.drawString(60, y, ann.message[:100])
        y -= 25

    p.showPage()
    p.save()
    return response













def is_admin(user):
    return user.groups.filter(name='Admin').exists()

@user_passes_test(is_admin)
def delete_attendance(request, id):
    ...



def attendance_chart_data(request):
    qs = Attendance.objects.all()

    if request.GET.get('service'):
        qs = qs.filter(service=request.GET['service'])

    data = (
        qs.values('date')
        .annotate(present=Count('id', filter=Q(present=True)))
        .order_by('date')
    )

    return JsonResponse({
        'labels': [d['date'] for d in data],
        'present': [d['present'] for d in data]
    })

class AdminRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return is_admin(self.request.user)


@require_POST
def ajax_toggle_attendance(request):
    attendance_id = request.POST.get('attendance_id')
    attendance = get_object_or_404(Attendance, id=attendance_id)

    attendance.present = not attendance.present
    attendance.save()

    return JsonResponse({
        'status': 'present' if attendance.present else 'absent'
    })
# -----------------------------
# Add Attendance (AJAX-friendly)
# -----------------------------
@login_required
def add_attendance(request):
    today = date.today()

    # --- GET PARAMETERS ---
    service_type = request.GET.get("service", "Sunday")
    search_query = request.GET.get("q", "").strip()
    selected_date_str = request.GET.get("date")

church_django/church_mgs/members/templates/partials/secretary_sidebar.html
<style>
    * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: Arial, sans-serif;
}

.layout {
    display: flex;
    height: 100vh;
}

/* Sidebar */
.sidebar {
    width: 250px;
    background: #1e293b;
    color: white;
    transition: width 0.3s ease;

    position: fixed;      /* KEY */
    top: 0;
    left: 0;
    height: 100vh;        /* Full screen */
    overflow-y: auto;     /* Scroll if menu grows */
}
.sidebar.collapsed {
    width: 70px;
}

.sidebar.collapsed ~ .content {
    margin-left: 70px;
}

.sidebar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px;
    background: #0f172a;
}

body {
    overflow-x: hidden;
}

.logo {
    font-size: 18px;
    font-weight: bold;
}

.toggle-btn {
    background: none;
    border: none;
    color: white;
    font-size: 20px;
    cursor: pointer;
}

.menu {
    list-style: none;
}

.menu li a {
    display: block;
    padding: 15px;
    color: white;
    text-decoration: none;
    white-space: nowrap;
}

.menu li a:hover {
    background: #334155;
}

/* Main content */

.content {
    margin-left: 250px;   /* SAME as sidebar width */
    padding: 20px;
    background: #f1f5f9;
    min-height: 100vh;
}



/* Submenu container */
.has-submenu .submenu {
    list-style: none;
    padding-left: 0;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.35s ease;
    background: #0f172a;
}

/* Expanded submenu */
.has-submenu.open .submenu {
    max-height: 300px; /* enough for items */
}

/* Submenu links */
.submenu li a {
    padding: 12px 20px 12px 45px;
    display: block;
    color: #cbd5e1;
    font-size: 14px;
}

.submenu li a:hover,
.submenu li a.active {
    background: #1d4ed8;
    color: #fff;
}

/* Arrow rotation */
.has-submenu .arrow {
    margin-left: auto;
    transition: transform 0.3s ease;
}

.has-submenu.open .arrow {
    transform: rotate(180deg);
}

</style>
<aside class="sidebar" id="sidebar">
    <div class="sidebar-header">
        <span class="logo">MyApp</span>
        <button class="toggle-btn" onclick="toggleSidebar()">☰</button>
    </div>

    <ul class="menu-item has-submenu">
        <li><a href="{% url 'members:post_login_redirect' %}">🏠 Dashboard</a></li>
        <li><a href="{% url 'members:member_list' %}">👥 Members</a></li>
        <li><a href="{% url 'members:add_attendance' %}">📅 Attendance</a></li>
        <li><a href="{% url 'members:promises_dashboard' %}">📢 Promise</a></li>
        <li><a href="{% url 'members:reports' %}">📊 Reports</a></li>
        <a href="{% url 'members:finance_dashboard' %}" class="submenu-toggle">
        <i class="bi bi-cash-stack"></i>
        <span>💰Finance</span>
        <i class="bi bi-chevron-down arrow"></i>
        </a>

        <ul class="submenu">
            <li>
                <a href="{% url 'members:finance_dashboard' %}" data-section="welfare">Overview</a>
            </li>
            <li>
                <a href="#" data-section="thanksgiving">Thanksgiving</a>
            </li>
            <li>
                <a href="#" data-section="welfare">Welfare</a>
            </li>
            <li>
                <a href="{% url 'members:tithes_dashboard' %}" data-section="tithes">Tithes</a>
            </li>
            <li>
                <a href="#" data-section="offering">Offering</a>
            </li>
            <li>
                <a href="#" data-section="ntintam">Ntintam</a>
            </li>
        </ul>
        <!--<li><a href="{% url 'members:finance_dashboard' %}">💰 Finance</a></li>--> 
        <li><a href="{% url 'members:secretary_settings' %}">⚙ Settings</a></li>
        <li><a href="{% url 'members:announcement_dashboard' %}">🚪 Announcement</a></li> 
    </ul>
     <br>





    <h3>Secretary Dashboard</h3>
<p>Welcome, {{ user.username }}!</p>
</aside>
<script>
function showSection(sectionId) {
    document.querySelectorAll('.finance-section').forEach(section => {
        section.classList.add('d-none');
    });

    document.getElementById(sectionId).classList.remove('d-none');

    document.querySelectorAll('.sidebar .nav-link').forEach(link => {
        link.classList.remove('active');
    });

    event.target.classList.add('active');
}


document.querySelectorAll('.submenu-toggle').forEach(toggle => {
    toggle.addEventListener('click', function (e) {
        e.preventDefault();
        this.parentElement.classList.toggle('open');
    });
});

// Active submenu item highlight
document.querySelectorAll('.submenu a').forEach(link => {
    link.addEventListener('click', function () {

        // Remove all active states
        document.querySelectorAll('.menu a').forEach(a =>
            a.classList.remove('active')
        );

        // Activate clicked item
        this.classList.add('active');

        // Keep parent open
        this.closest('.has-submenu').classList.add('open');
    });
});

document.querySelectorAll('[data-section]').forEach(link => {
    link.addEventListener('click', function () {
        const target = this.dataset.section;

        document.querySelectorAll('.finance-section').forEach(section =>
            section.classList.add('d-none')
        );

        document.getElementById(target).classList.remove('d-none');
    });
});

</script>

   